export const subjectTopics = {
  "General Aptitude": ["Verbal Ability", "Numerical Ability", "Analytical Aptitude", "Spatial Aptitude"],
  "Engineering Mathematics": ["Linear Algebra", "Calculus", "Probability and Statistics"],
  "Discrete Mathematics": [
    "Set Theory",
    "Relations and Functions",
    "Mathematical Logic",
    "Combinatorics",
    "Graph Theory",
    "Recurrence Relations",
    "Mathematical Induction",
    "Number Theory",
    "Boolean Algebra",
    "Lattice Theory",
  ],
  "Digital Logic": [
    "Boolean Algebra",
    "Combinational and Sequential Circuits",
    "Minimization",
    "Number Representations",
    "Computer Arithmetic",
  ],
  "Computer Organization and Architecture": [
    "Machine Instructions and Addressing Modes",
    "ALU, Data-path and Control Unit",
    "Instruction Pipelining",
    "Memory Hierarchy",
    "I/O Interface",
  ],
  "Programming and Data Structures": [
    "Programming in C",
    "Recursion",
    "Arrays",
    "Stacks",
    "Queues",
    "Linked Lists",
    "Trees",
    "Binary Search Trees",
    "Binary Heaps",
    "Graphs",
  ],
  Algorithms: [
    "Searching",
    "Sorting",
    "Hashing",
    "Asymptotic Complexity",
    "Algorithm Design Techniques",
    "Graph Traversals",
    "Minimum Spanning Trees",
    "Shortest Paths",
  ],
  "Theory of Computation": [
    "Regular Expressions and Finite Automata",
    "Context-Free Grammars and Push-Down Automata",
    "Regular and Context-Free Languages",
    "Pumping Lemma",
    "Turing Machines",
    "Undecidability",
  ],
  "Compiler Design": [
    "Lexical Analysis",
    "Parsing",
    "Syntax-Directed Translation",
    "Runtime Environments",
    "Intermediate Code Generation",
    "Local Optimization",
    "Data Flow Analyses",
  ],
  "Operating Systems": [
    "System Calls",
    "Processes",
    "Threads",
    "Inter-Process Communication",
    "Concurrency and Synchronization",
    "Deadlock",
    "CPU and I/O Scheduling",
    "Memory Management",
    "Virtual Memory",
    "File Systems",
  ],
  Databases: [
    "ER-Model",
    "Relational Model",
    "Relational Algebra",
    "Tuple Calculus",
    "SQL",
    "Integrity Constraints",
    "Normal Forms",
    "File Organization",
    "Indexing",
    "Transactions",
    "Concurrency Control",
  ],
  "Computer Networks": [
    "Concept of Layering",
    "OSI and TCP/IP Protocol Stacks",
    "Packet, Circuit, and Virtual Circuit Switching",
    "Data Link Layer",
    "Routing Protocols",
    "IP Addressing",
    "IPv4",
    "CIDR Notation",
    "Transport Layer",
    "Application Layer Protocols",
  ]
} as const

export type SubjectName = keyof typeof subjectTopics

